### PR TITLE
Cykhash package: Fix recipe (do not use noarch)

### PR DESCRIPTION
**Pull request by HTenkanen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixing the recipe as the package is mainly written with Cython (no noarch).

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Why are you removing the ``noarch: python``?

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by HTenkanen** [comment]
@marcelotrevisani Hi! Because, this is a Cython package and I was advised to do so. I asked about this in Gitter a few moments ago: https://gitter.im/conda-forge/conda-forge.github.io 

Is this okay?

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani Hi! Because, this is a Cython package and I was advised to do so. I asked about this in Gitter a few moments ago: https://gitter.im/conda-forge/conda-forge.github.io
> 
> Is this okay?

Yes, I just saw that you are using the compilers and cython and I deleted my comment :grimacing:

**Comment by marcelotrevisani** [comment]
You will need to rerender the feedstock, I just called the bot, lets wait for it

**Comment by HTenkanen** [comment]
@marcelotrevisani Okay, good thanks! This is the first time I do these things, so still learning.. So thanks for double-checking! 🙂

**Comment by HTenkanen** [comment]
@marcelotrevisani Okay, it seems that all the checks passed and the builds were successful. Is it now okay for me to merge this pull request, or should someone from the conda-forge team do it (such as you)? Just trying to understand the full workflow..

**Comment by marcelotrevisani** [comment]
You can go ahead and merge it. As you are the maintainer of this project/recipe you can merge whenever you are satisfied with the modifications :)

**Comment by HTenkanen** [comment]
@marcelotrevisani Perfect! Thanks a lot for your help! 💪

**Pull request merged**
